from __future__ import annotations

from .repository_metadata_family import RepositoryMetadataConfig


CATALOG_JSON_CONFIGS: dict[str, RepositoryMetadataConfig] = {
    "chicago_open_data": RepositoryMetadataConfig(
        source_skill_id="chicago_open_data",
        source_card_id="chicago_open_data_socrata_catalog",
        publisher="City of Chicago",
        landing_url="https://data.cityofchicago.org/",
        docs_url="https://dev.socrata.com/docs/other/catalog.html",
        search_url="https://api.us.socrata.com/api/catalog/v1",
        source_family="socrata_catalog_api",
        resolver_family="socrata_catalog_domain_search",
        entity_label="Chicago open data catalog",
        route_description="Socrata catalog search constrained to the City of Chicago open data domain.",
        result_path=("results",),
        required_item_keys=("resource",),
        sample_filename="chicago_open_data_catalog_sample.json",
        access_method="socrata_catalog_search",
        query_params=(
            ("domains", "data.cityofchicago.org"),
            ("search_context", "data.cityofchicago.org"),
            ("q", "{query}"),
            ("limit", "10"),
        ),
        validation_notes=(
            "Validate Socrata four-by-four identifiers, resource type, row-level API availability, and field metadata before download.",
            "Use resource-specific SODA endpoints only after the catalog item has been selected.",
        ),
    ),
    "london_datastore": RepositoryMetadataConfig(
        source_skill_id="london_datastore",
        source_card_id="london_datastore_ckan_catalog",
        publisher="Greater London Authority",
        landing_url="https://data.london.gov.uk/",
        docs_url="https://docs.ckan.org/en/latest/api/",
        search_url="https://data.london.gov.uk/api/3/action/package_search",
        source_family="ckan_catalog_api",
        resolver_family="ckan_package_search",
        entity_label="London Datastore catalog",
        route_description="CKAN package search over the Greater London Authority London Datastore.",
        result_path=("result", "result"),
        required_item_keys=("id", "name", "title"),
        sample_filename="london_datastore_catalog_sample.json",
        access_method="ckan_package_search",
        query_params=(("q", "{query}"), ("rows", "10")),
    ),
    "data_gov_catalog": RepositoryMetadataConfig(
        source_skill_id="data_gov_catalog",
        source_card_id="data_gov_catalog_v4_api",
        publisher="U.S. General Services Administration",
        landing_url="https://catalog.data.gov/",
        docs_url="https://resources.data.gov/catalog-api/",
        search_url="https://api.gsa.gov/technology/datagov/v4/search",
        source_family="data_gov_catalog_api",
        resolver_family="data_gov_v4_catalog_search",
        entity_label="Data.gov catalog",
        route_description="Data.gov v4 Catalog API search over U.S. federal, state, local, and tribal dataset metadata.",
        result_path=("results",),
        required_item_keys=("dcat",),
        sample_filename="data_gov_catalog_sample.json",
        access_method="data_gov_v4_search_api",
        query_params=(("q", "{query}"), ("page_size", "10"), ("api_key", "DEMO_KEY")),
        validation_notes=(
            "The legacy catalog.data.gov CKAN endpoint now redirects poorly for API clients; use the GSA v4 Catalog API.",
            "DEMO_KEY is acceptable for exploration; production workflows should provide a registered api.data.gov key.",
        ),
        requestability_conditions=(
            "The query resolves through the GSA v4 Catalog API.",
            "A valid api.data.gov key is available for production or automated querying.",
            "Selected DCAT distributions expose reusable accessURL or downloadURL fields.",
        ),
    ),
    "hdx_catalog": RepositoryMetadataConfig(
        source_skill_id="hdx_catalog",
        source_card_id="hdx_catalog_ckan_api",
        publisher="OCHA",
        landing_url="https://data.humdata.org/",
        docs_url="https://data.humdata.org/api/3/action/help_show?name=package_search",
        search_url="https://data.humdata.org/api/3/action/package_search",
        source_family="ckan_catalog_api",
        resolver_family="hdx_ckan_package_search",
        entity_label="Humanitarian Data Exchange catalog",
        route_description="HDX CKAN package search for humanitarian datasets and resource metadata.",
        result_path=("result", "results"),
        required_item_keys=("id", "name", "title"),
        sample_filename="hdx_catalog_sample.json",
        access_method="ckan_package_search",
        query_params=(("q", "{query}"), ("rows", "10")),
        validation_notes=(
            "Validate humanitarian geography, update cadence, resource format, caveats, and HDX license before use.",
            "Some HDX resources may require contributor-specific interpretation even when metadata is public.",
        ),
    ),
    "hong_kong_data_gov": RepositoryMetadataConfig(
        source_skill_id="hong_kong_data_gov",
        source_card_id="hong_kong_data_gov_ckan_api",
        publisher="Hong Kong SAR Government",
        landing_url="https://data.gov.hk/",
        docs_url="https://data.gov.hk/en-data/api/3/action/help_show?name=package_search",
        search_url="https://data.gov.hk/en-data/api/3/action/package_search",
        source_family="ckan_catalog_api",
        resolver_family="hong_kong_ckan_package_search",
        entity_label="Hong Kong data.gov.hk catalog",
        route_description="data.gov.hk CKAN package search for Hong Kong public dataset metadata.",
        result_path=("result", "results"),
        required_item_keys=("id", "name", "title"),
        sample_filename="hong_kong_data_gov_catalog_sample.json",
        access_method="ckan_package_search",
        query_params=(("q", "{query}"), ("rows", "10")),
    ),
    "singapore_data_gov": RepositoryMetadataConfig(
        source_skill_id="singapore_data_gov",
        source_card_id="singapore_data_gov_dataset_listing",
        publisher="Government of Singapore",
        landing_url="https://data.gov.sg/",
        docs_url="https://guide.data.gov.sg/developer-guide/dataset-apis/list-all-datasets",
        search_url="https://api-production.data.gov.sg/v2/public/api/datasets",
        source_family="data_gov_sg_dataset_api",
        resolver_family="data_gov_sg_dataset_listing",
        entity_label="data.gov.sg dataset listing",
        route_description="data.gov.sg public dataset listing API; filter returned dataset metadata locally against the user query.",
        result_path=("data", "datasets"),
        required_item_keys=("datasetId", "name"),
        sample_filename="singapore_data_gov_dataset_listing_sample.json",
        access_method="data_gov_sg_dataset_listing_api",
        query_params=(("page", "1"),),
        required_inputs=(),
        validation_notes=(
            "The listing API enumerates datasets; use dataset metadata and datastore/download APIs after selecting a datasetId.",
            "Treat query, geography, and time_range as local filtering hints because this endpoint does not expose full-text search.",
        ),
    ),
}


def get_catalog_json_config(source_skill_id: str) -> RepositoryMetadataConfig:
    return CATALOG_JSON_CONFIGS[source_skill_id]
