from __future__ import annotations

from .api_payload_family import ApiPayloadConfig


PUBLIC_API_PAYLOAD_CONFIGS: dict[str, ApiPayloadConfig] = {
    "world_bank_indicators": ApiPayloadConfig(
        source_skill_id="world_bank_indicators",
        publisher="World Bank",
        metadata_url="https://api.worldbank.org/v2/",
        sample_filename="world_bank_indicators_sample.json",
        payload_label="indicator_api",
        result_path=(1,),
        required_item_keys=("country.id", "indicator.id", "date", "value"),
    ),
    "open_aq": ApiPayloadConfig(
        source_skill_id="open_aq",
        publisher="OpenAQ",
        metadata_url="https://docs.openaq.org/",
        sample_filename="open_aq_measurements_sample.json",
        payload_label="measurements_api",
        result_path=("results",),
        required_item_keys=("value", "period.datetimeFrom.utc", "parameter.name"),
        required_top_level_keys=("results",),
        credential_required=True,
        credential_label="api_key",
        credential_env_var="OPENAQ_API_KEY",
        credential_header_name="X-API-Key",
    ),
    "eia_energy": ApiPayloadConfig(
        source_skill_id="eia_energy",
        publisher="U.S. Energy Information Administration",
        metadata_url="https://api.eia.gov/v2/",
        sample_filename="eia_energy_api_sample.json",
        payload_label="api_v2",
        result_path=("response", "data"),
        required_item_keys=("period",),
        required_top_level_keys=("response",),
        credential_required=True,
        credential_label="api_key",
        credential_env_var="EIA_API_KEY",
        credential_query_param="api_key",
    ),
    "bls_local_economy": ApiPayloadConfig(
        source_skill_id="bls_local_economy",
        publisher="U.S. Bureau of Labor Statistics",
        metadata_url="https://api.bls.gov/publicAPI/v2/timeseries/data/",
        sample_filename="bls_local_economy_sample.json",
        payload_label="timeseries_api",
        result_path=("Results", "series"),
        required_item_keys=("seriesID", "data"),
        required_top_level_keys=("status", "Results"),
    ),
    "usgs_hydro": ApiPayloadConfig(
        source_skill_id="usgs_hydro",
        publisher="U.S. Geological Survey",
        metadata_url="https://waterservices.usgs.gov/",
        sample_filename="usgs_hydro_water_services_sample.json",
        payload_label="water_services",
        result_path=("value", "timeSeries"),
        required_item_keys=("sourceInfo", "variable", "values"),
        required_top_level_keys=("value",),
    ),
    "noaa_weather": ApiPayloadConfig(
        source_skill_id="noaa_weather",
        publisher="NOAA National Centers for Environmental Information",
        metadata_url="https://www.ncdc.noaa.gov/cdo-web/webservices/v2",
        sample_filename="noaa_cdo_weather_sample.json",
        payload_label="cdo_api",
        result_path=("results",),
        required_item_keys=("date", "datatype", "station", "value"),
        required_top_level_keys=("results",),
        credential_required=True,
        credential_label="token",
        credential_env_var="NOAA_CDO_TOKEN",
        credential_header_name="token",
    ),
    "nws_weather_forecast": ApiPayloadConfig(
        source_skill_id="nws_weather_forecast",
        publisher="NOAA National Weather Service",
        metadata_url="https://www.weather.gov/documentation/services-web-api",
        sample_filename="nws_weather_forecast_sample.json",
        payload_label="forecast_api",
        result_path=("properties", "periods"),
        required_item_keys=("name", "startTime", "endTime", "temperature", "shortForecast"),
        required_top_level_keys=("properties",),
    ),
    "un_sdg_indicators": ApiPayloadConfig(
        source_skill_id="un_sdg_indicators",
        publisher="United Nations Statistics Division",
        metadata_url="https://unstats.un.org/SDGAPI/swagger/v1/swagger.json",
        sample_filename="un_sdg_indicators_sample.json",
        payload_label="series_data_api",
        result_path=("data",),
        required_item_keys=("seriesCode", "geoAreaCode", "timePeriod", "value"),
        required_top_level_keys=("data",),
    ),
    "epa_air_quality": ApiPayloadConfig(
        source_skill_id="epa_air_quality",
        publisher="U.S. Environmental Protection Agency",
        metadata_url="https://aqs.epa.gov/aqsweb/documents/data_api.html",
        sample_filename="epa_air_quality_aqs_sample.json",
        payload_label="aqs_api",
        result_path=("Data",),
        required_item_keys=("state_code", "parameter_code", "sample_measurement"),
        required_top_level_keys=("Header", "Data"),
        credential_required=True,
        credential_label="api_key",
        credential_env_var="EPA_AQS_API_KEY",
        credential_query_param="key",
    ),
    "cdc_places": ApiPayloadConfig(
        source_skill_id="cdc_places",
        publisher="Centers for Disease Control and Prevention",
        metadata_url="https://chronicdata.cdc.gov/",
        sample_filename="cdc_places_socrata_sample.json",
        payload_label="socrata_api",
        result_path=None,
        required_item_keys=("year", "locationname", "data_value"),
    ),
    "hifld_facilities": ApiPayloadConfig(
        source_skill_id="hifld_facilities",
        publisher="Homeland Infrastructure Foundation-Level Data",
        metadata_url="https://services.arcgis.com/XG15cJAlne2vxtgt/arcgis/rest/services",
        sample_filename="hifld_arcgis_query_sample.json",
        payload_label="arcgis_query",
        result_path=("features",),
        required_item_keys=("attributes", "geometry"),
        required_top_level_keys=("features",),
    ),
    "gbfs_bikeshare": ApiPayloadConfig(
        source_skill_id="gbfs_bikeshare",
        publisher="MobilityData / GBFS systems",
        metadata_url="https://gbfs.org/",
        sample_filename="gbfs_feed_sample.json",
        payload_label="gbfs_feed",
        result_path=("data", "feeds"),
        required_item_keys=("name", "url"),
        required_top_level_keys=("data",),
    ),
    "transitland": ApiPayloadConfig(
        source_skill_id="transitland",
        publisher="Transitland",
        metadata_url="https://www.transit.land/documentation/datastore/api-endpoints.html",
        sample_filename="transitland_feed_search_sample.json",
        payload_label="feed_search_api",
        result_path=("feeds",),
        required_item_keys=("id", "onestop_id"),
        required_top_level_keys=("feeds",),
    ),
    "data_commons": ApiPayloadConfig(
        source_skill_id="data_commons",
        publisher="Data Commons",
        metadata_url="https://docs.datacommons.org/api/rest/v2/",
        sample_filename="data_commons_observation_sample.json",
        payload_label="observation_api",
        result_path=("observationsByVariable",),
        required_top_level_keys=("observationsByVariable",),
    ),
    "mobility_database": ApiPayloadConfig(
        source_skill_id="mobility_database",
        publisher="MobilityData",
        metadata_url="https://mobilitydatabase.org/",
        sample_filename="mobility_database_search_sample.json",
        payload_label="catalog_search_api",
        result_path=("results",),
        required_item_keys=("id", "name"),
        required_top_level_keys=("results",),
    ),
    "worldpop": ApiPayloadConfig(
        source_skill_id="worldpop",
        publisher="WorldPop",
        metadata_url="https://www.worldpop.org/rest/",
        sample_filename="worldpop_api_sample.json",
        payload_label="rest_api",
        result_path=("data",),
        required_item_keys=("id", "title"),
        required_top_level_keys=("data",),
    ),
    "geoboundaries": ApiPayloadConfig(
        source_skill_id="geoboundaries",
        publisher="geoBoundaries",
        metadata_url="https://www.geoboundaries.org/api.html",
        sample_filename="geoboundaries_api_sample.json",
        payload_label="api",
        result_path=None,
        required_item_keys=("boundaryID", "gjDownloadURL"),
    ),
    "osm_features": ApiPayloadConfig(
        source_skill_id="osm_features",
        publisher="OpenStreetMap / Overpass API",
        metadata_url="https://wiki.openstreetmap.org/wiki/Overpass_API",
        sample_filename="osm_overpass_sample.json",
        payload_label="overpass_api",
        result_path=("elements",),
        required_item_keys=("type", "id"),
        required_top_level_keys=("elements",),
    ),
}


def get_public_api_payload_config(source_skill_id: str) -> ApiPayloadConfig:
    return PUBLIC_API_PAYLOAD_CONFIGS[source_skill_id]
