from __future__ import annotations

from .direct_file_family import DirectFileConfig


REMAINING_DIRECT_FILE_CONFIGS: dict[str, DirectFileConfig] = {
    "snap_brightkite": DirectFileConfig(
        source_skill_id="snap_brightkite",
        source_card_id="snap_brightkite_open_data",
        publisher="Stanford Network Analysis Project",
        landing_url="https://snap.stanford.edu/data/loc-brightkite.html",
        docs_url="https://snap.stanford.edu/data/loc-brightkite.html",
        url_template="https://snap.stanford.edu/data/loc-brightkite_totalCheckins.txt.gz",
        source_family="snap_brightkite_static_gzip",
        resolver_family="snap_brightkite_direct_file",
        entity_label="SNAP Brightkite check-in and friendship files",
        route_description="Official SNAP Brightkite gzip files; select checkins or friendship edges with the source-specific resolver before fetching.",
        sample_filename="snap_brightkite_sample.txt.gz",
        expected_suffixes=(".txt.gz", ".gz"),
        expected_magic_prefixes=(b"\x1f\x8b",),
        validation_notes=(
            "Confirm gzip magic bytes before accepting a direct-file response.",
            "Check-in rows are tab-separated and can contain three to five fields; friendship edges contain two IDs.",
        ),
    ),
    "viirs_nighttime_lights": DirectFileConfig(
        source_skill_id="viirs_nighttime_lights",
        source_card_id="viirs_nighttime_lights",
        publisher="NOAA / Colorado School of Mines",
        landing_url="https://eogdata.mines.edu/products/vnl/",
        docs_url="https://eogdata.mines.edu/products/vnl/",
        url_template="https://eogdata.mines.edu/nighttime_light/annual/v22/{time_range}/VNL_v22_npp_{time_range}_global_vcmslcfg_c202303062300.average.dat.tif.gz",
        source_family="viirs_nighttime_lights_direct_file",
        resolver_family="viirs_yearly_raster_file",
        entity_label="VIIRS nighttime lights annual raster",
        route_description="VIIRS annual nighttime lights raster URL template; validate year/version and file availability before full fetch.",
        sample_filename="viirs_nighttime_lights_sample.tif.gz",
        expected_suffixes=(".tif.gz", ".tif", ".zip"),
        required_inputs=("time_range",),
    ),
    "us_tiger_boundaries": DirectFileConfig(
        source_skill_id="us_tiger_boundaries",
        source_card_id="us_tiger_boundaries",
        publisher="U.S. Census Bureau",
        landing_url="https://www.census.gov/geographies/mapping-files/time-series/geo/tiger-line-file.html",
        docs_url="https://www2.census.gov/geo/tiger/TIGER2024/",
        url_template="https://www2.census.gov/geo/tiger/TIGER{time_range}/{query}/tl_{time_range}_{geography}_{query}.zip",
        source_family="census_tiger_direct_zip",
        resolver_family="tiger_year_layer_geography_zip",
        entity_label="U.S. Census TIGER/Line boundary files",
        route_description="TIGER/Line direct ZIP URL template for year, layer, and geography.",
        sample_filename="us_tiger_boundary_sample.zip",
        expected_suffixes=(".zip",),
        required_inputs=("query", "geography", "time_range"),
    ),
    "overture_maps": DirectFileConfig(
        source_skill_id="overture_maps",
        source_card_id="overture_maps",
        publisher="Overture Maps Foundation",
        landing_url="https://docs.overturemaps.org/",
        docs_url="https://docs.overturemaps.org/getting-data/",
        url_template="s3://overturemaps-us-west-2/release/{time_range}/theme={query}/type={geography}/",
        source_family="overture_maps_public_parquet",
        resolver_family="overture_release_theme_type_partition",
        entity_label="Overture Maps public parquet release",
        route_description="Overture Maps public S3 partition prefix for release, theme, and type.",
        sample_filename="overture_maps_sample.parquet",
        expected_suffixes=(".parquet",),
        required_inputs=("query", "geography", "time_range"),
    ),
    "nlcd_land_cover": DirectFileConfig(
        source_skill_id="nlcd_land_cover",
        source_card_id="nlcd_land_cover",
        publisher="Multi-Resolution Land Characteristics Consortium",
        landing_url="https://www.mrlc.gov/data",
        docs_url="https://www.mrlc.gov/data",
        url_template="https://www.mrlc.gov/downloads/sciweb1/shared/mrlc/data-bundles/nlcd_{time_range}_land_cover_l48_20230630.zip",
        source_family="nlcd_direct_zip",
        resolver_family="nlcd_year_product_zip",
        entity_label="NLCD land cover raster bundle",
        route_description="NLCD direct ZIP bundle template for land-cover year.",
        sample_filename="nlcd_land_cover_sample.zip",
        expected_suffixes=(".zip",),
        required_inputs=("time_range",),
    ),
    "lehd_lodes": DirectFileConfig(
        source_skill_id="lehd_lodes",
        source_card_id="lehd_lodes",
        publisher="U.S. Census Bureau",
        landing_url="https://lehd.ces.census.gov/data/",
        docs_url="https://lehd.ces.census.gov/data/lodes/LODES8/",
        url_template="https://lehd.ces.census.gov/data/lodes/LODES8/{geography}/wac/{geography}_wac_S000_JT00_{time_range}.csv.gz",
        source_family="lehd_lodes_direct_csv_gz",
        resolver_family="lodes_state_file_template",
        entity_label="LEHD LODES files",
        route_description="LEHD LODES state CSV.GZ URL template for workplace area characteristics.",
        sample_filename="lehd_lodes_sample.csv.gz",
        expected_suffixes=(".csv.gz", ".csv"),
        required_inputs=("geography", "time_range"),
    ),
    "inside_airbnb": DirectFileConfig(
        source_skill_id="inside_airbnb",
        source_card_id="inside_airbnb",
        publisher="Inside Airbnb",
        landing_url="https://insideairbnb.com/get-the-data/",
        docs_url="https://insideairbnb.com/get-the-data/",
        url_template="https://data.insideairbnb.com/{geography}/{time_range}/data/listings.csv.gz",
        source_family="inside_airbnb_direct_csv_gz",
        resolver_family="inside_airbnb_city_date_file",
        entity_label="Inside Airbnb city snapshots",
        route_description="Inside Airbnb direct listings CSV.GZ template for city path and snapshot date.",
        sample_filename="inside_airbnb_listings_sample.csv.gz",
        expected_suffixes=(".csv.gz", ".csv"),
        required_inputs=("geography", "time_range"),
    ),
    "ghsl_urban_extent": DirectFileConfig(
        source_skill_id="ghsl_urban_extent",
        source_card_id="ghsl_urban_extent",
        publisher="European Commission Joint Research Centre",
        landing_url="https://ghsl.jrc.ec.europa.eu/download.php",
        docs_url="https://ghsl.jrc.ec.europa.eu/download.php",
        url_template="https://jeodpp.jrc.ec.europa.eu/ftp/jrc-opendata/GHSL/{query}/{time_range}/",
        source_family="ghsl_download_prefix",
        resolver_family="ghsl_product_epoch_file",
        entity_label="GHSL urban extent products",
        route_description="GHSL product/year download prefix; resolve concrete raster ZIP before full fetch.",
        sample_filename="ghsl_urban_extent_sample.zip",
        expected_suffixes=(".zip", ".tif"),
        required_inputs=("query", "time_range"),
    ),
    "cdc_svi": DirectFileConfig(
        source_skill_id="cdc_svi",
        source_card_id="cdc_svi",
        publisher="Centers for Disease Control and Prevention",
        landing_url="https://www.atsdr.cdc.gov/placeandhealth/svi/data_documentation_download.html",
        docs_url="https://www.atsdr.cdc.gov/placeandhealth/svi/data_documentation_download.html",
        url_template="https://www.atsdr.cdc.gov/placeandhealth/svi/data_documentation_download.html",
        source_family="cdc_svi_download_landing",
        resolver_family="cdc_svi_year_geography_file",
        entity_label="CDC Social Vulnerability Index files",
        route_description="CDC SVI official download landing; resolve year/geography CSV or shapefile before full fetch.",
        sample_filename="cdc_svi_sample.csv",
        expected_suffixes=(".csv", ".zip"),
        required_inputs=(),
    ),
    "brfss_raw": DirectFileConfig(
        source_skill_id="brfss_raw",
        source_card_id="cdc_brfss_annual_public_use",
        publisher="Centers for Disease Control and Prevention",
        landing_url="https://www.cdc.gov/brfss/annual_data/annual_data.htm",
        docs_url="https://www.cdc.gov/brfss/data_documentation/index.htm",
        url_template="https://www.cdc.gov/brfss/annual_data/{time_range}/files/LLCP{time_range}XPT.zip",
        source_family="cdc_brfss_annual_public_use_xpt_zip",
        resolver_family="brfss_year_xpt_zip",
        entity_label="CDC BRFSS annual public-use microdata",
        route_description="CDC BRFSS annual public-use XPT ZIP URL template; validate year page, codebook, and survey documentation before acquisition.",
        sample_filename="brfss_raw_xpt_sample.zip",
        expected_suffixes=(".zip",),
        required_inputs=("time_range",),
    ),
}


def get_remaining_direct_file_config(source_skill_id: str) -> DirectFileConfig:
    return REMAINING_DIRECT_FILE_CONFIGS[source_skill_id]
